services:
  backend:
    image: tomsterauds/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db
      - media_data:/app/media
    environment:
      - DEBUG=True
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 5
      start_period: 20s

  frontend:
    image: tomsterauds/frontend:latest
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  sqlite_data:
  media_data:
